apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: fast-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080   # optional: you can omit this and let Kubernetes choose
  type: NodePort
