name: Reusable - Docker Build

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      dockerfile_path:
        required: true
        type: string
      context:
        required: true
        type: string

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: List directory contents
        run: ls -la ${{ inputs.context }}

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t ${{ inputs.service_name }} -f ${{ inputs.dockerfile_path }} ${{ inputs.context }}