apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-container
          image: {{ .Values.backend.image }}:{{ .Values.backend.tag }}
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
        - name: otel collector endpoint
          value: "http://otel-collector.monitoring.svc.cluster.local:4317"
          
        - name: otel service name
          value: "fastapi-backend"

