apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  labels:
    app: otel-collector
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:

    exporters:
      otlphttp/datadog:
        endpoint: "https://api.datadoghq.com/api/v2/otel/v1/traces"
        headers:
          DD-API-KEY: {{ .Values.datadog.apiKey }}

      otlphttp/newrelic:
        endpoint: "https://otlp.nr-data.net/v1/traces"
        headers:
          api-key: {{ .Values.newrelic.licenseKey }}

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/datadog, otlphttp/newrelic]
