apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  labels:
    app: otel-collector
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    exporters:
      otlphttp/datadog:
        endpoint: "https://api.datadoghq.com"
        headers:
          DD-API-KEY: ${DATADOG_API_KEY}

      otlphttp/newrelic:
        endpoint: "https://otlp.nr-data.net"
        headers:
          api-key: ${NEW_RELIC_API_KEY}

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlphttp/datadog, otlphttp/newrelic]
