backend:
  image: saotech/k8s_backend
  tag: 35b112d11b94163306fe6c12cf46966b8985a2f6
  replicas: 1
  containerPort: 8000
  servicePort: 8000

ingress:
  enabled: true
  hostname: backend.local
  servicePort: 8000
  path: /docs

