backend:
  image: saotech/k8s_backend
  tag: 236f162590a98067e35329e31d6cf32a75821176
  replicas: 1
  containerPort: 8000
  servicePort: 8000

ingress:
  enabled: true
  hostname: backend.local
  servicePort: 8000
  path: /docs

