backend:
  image: saotech/k8s_backend
  tag: 324a649e48d07c896e54e8f109c126f095f36a56
  replicas: 1
  containerPort: 8000
  servicePort: 8000

ingress:
  enabled: true
  hostname: backend.local
  servicePort: 8000
  path: /docs

