backend:
  image: saotech/k8s_backend
  tag: a912ad7c0aeaa2e48b99d24cf4b05b0256fdefb1
  replicas: 1
  containerPort: 8000
  servicePort: 8000

ingress:
  enabled: true
  hostname: localhost
  servicePort: 8000
  path: /

