backend:
  image: saotech/k8s_backend
  tag: e7c9d605b8b42810bf086b38ac27245750943324
  replicas: 1
  containerPort: 8000
  servicePort: 8000

ingress:
  enabled: true
  hostname: backend.local
  servicePort: 8000
  path: /docs

