backend:
  image: saotech/k8s_backend
  tag: d4cece9102036602c75d7d639ba9811ec0f5ac25
  replicas: 1
  containerPort: 8000
  servicePort: 8000

ingress:
  enabled: true
  hostname: backend.local
  servicePort: 8000
  path: /docs

