image:
  repository: saotech/k8s_frontend_ui
  tag: d7ada6d7c82fec822b7ead4cb59da8e6ea3df5ed
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix
  tls: []
