image:
  repository: your-dockerhub-user/k8s_frontend
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: frontend.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

env:
  - name: VITE_API_URL
    value: http://backend-service.default.svc.cluster.local:8000

resources: {}