apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  selector:
    app: react-frontend
  ports:
    - port: {{ .Values.frontend.servicePort }}
      targetPort: {{ .Values.frontend.containerPort }}
  type: ClusterIP
