apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: argocd
type: Opaque
stringData:
  username: user
  password: pass
  database: mydb
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: argocd
type: Opaque
stringData:
  password: password
