apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: a-backend-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/DevOpsByOmer/Projects'
    targetRevision: main
    path: helm-charts/a-backend

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
