version: "3.8"

services:
 frontend:
  build: ./apps/frontend-dashboard/react-app/
  ports:
    - "80:80"
  depends_on:
    - backend
  environment:
    - REACT_APP_API_URL=http://backend:8000

 backend: 
    build: ./apps/backend-api/Fapi-1/
    ports:
    - "8000:8000"



  
