replicaCount: 1

image:
  repository: saotech/k8s_backend_api
  tag: cc39fb7443f0cc1a4c34ef2c00c4e79d891f31ad
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

env:
  # PostgreSQL config
  - name: POSTGRES_SERVER
    value: postgres.argocd.svc.cluster.local
  - name: POSTGRES_PORT
    value: "5432"
  - name: POSTGRES_DB
    valueFrom:
      secretKeyRef:
        name: postgres-secret
        key: database
  - name: POSTGRES_USER
    valueFrom:
      secretKeyRef:
        name: postgres-secret
        key: username
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres-secret
        key: password

  # Redis config
  - name: REDIS_HOST
    value: redis.argocd.svc.cluster.local
  - name: REDIS_PORT
    value: "6379"
  - name: REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: redis-secret
        key: password

  # Required for FastAPI settings
  - name: PROJECT_NAME
    value: "BackendApp"
  - name: FIRST_SUPERUSER
    value: "admin@example.com"
  - name: FIRST_SUPERUSER_PASSWORD
    valueFrom:
      secretKeyRef:
        name: backend-secret
        key: first_superuser_password

resources: {}

livenessProbe:
  path: /api/v1/utils/health-check/
  port: 8000

readinessProbe:
  path: /api/v1/utils/health-check/
  port: 8000
