replicaCount: 1

image:
  repository: saotech/k8s_backend_api
  tag: cc39fb7443f0cc1a4c34ef2c00c4e79d891f31ad
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

env:
  # PostgreSQL config
  POSTGRES_SERVER: postgres.argocd.svc.cluster.local
  POSTGRES_PORT: "5432"
  POSTGRES_DB:
    secretKeyRef:
      name: postgres-secret
      key: database
  POSTGRES_USER:
    secretKeyRef:
      name: postgres-secret
      key: username
  POSTGRES_PASSWORD:
    secretKeyRef:
      name: postgres-secret
      key: password

  # Redis config
  REDIS_HOST: redis.argocd.svc.cluster.local
  REDIS_PORT: "6379"
  REDIS_PASSWORD:
    secretKeyRef:
      name: redis-secret
      key: password

resources: {}

livenessProbe:
  path: /api/v1/utils/health-check/
  port: 8000

readinessProbe:
  path: /api/v1/utils/health-check/
  port: 8000
