frontend:
  image: saotech/k8s_frontend
  tag: 78726673b1b4ab4be5a73a552b577144e9d05479
  replicas: 1
  containerPort: 80
  servicePort: 80

ingress:
  enabled: true
  hostname: frontend.local
  servicePort: 80
  path: /


