frontend:
  image: k8s_frontend
  tag: e1f3f3df76851887374816b40876b701e2ac0dec
  replicas: 1
  containerPort: 80
  servicePort: 80

ingress:
  enabled: true
  hostname: frontend.local
  servicePort: 80
  path: /


