frontend:
  image: saotech/k8s_frontend
  tag: 966c622c76cb19dc19e75ad0bbb4b1e75173607d
  replicas: 1
  containerPort: 80
  servicePort: 80

ingress:
  enabled: true
  hostname: frontend.local
  servicePort: 80
  path: /


