backend:
  image: saotech/k8s_backend
  tag: 5bd709498c7814c78d19d14a5afc7a4e7a514add
  replicas: 1
  containerPort: 8000
  servicePort: 8000

ingress:
  enabled: true
  hostname: backend.local
  servicePort: 8000
  path: /docs

