backend:
  image: saotech/k8s_backend
  tag: 9ff1c2ae9e2608ee93e4a0c6d58b436cfc7cfebd
  replicas: 1
  containerPort: 8000
  servicePort: 8000

ingress:
  enabled: true
  hostname: backend.local
  servicePort: 8000
  path: /docs

