backend:
  image: k8s_backend
  tag: e1f3f3df76851887374816b40876b701e2ac0dec
  replicas: 1
  containerPort: 8000
  servicePort: 8000

ingress:
  enabled: true
  hostname: backend.local
  servicePort: 8000
  path: /docs

