backend:
  image: k8s_backend
  tag: 78726673b1b4ab4be5a73a552b577144e9d05479
  replicas: 1
  containerPort: 8000
  servicePort: 8000

ingress:
  enabled: true
  hostname: backend.local
  servicePort: 8000
  path: /docs

