mode: deployment

image:
  repository: otel/opentelemetry-collector
  tag: "0.85.0"

configMap:
  create: true
  name: otel-collector-config
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    exporters:
      otlphttp/datadog:
        endpoint: "https://api.datadoghq.com"
        headers:
          DD-API-KEY: ${DATADOG_API_KEY}

      otlphttp/newrelic:
        endpoint: "https://otlp.nr-data.net"
        headers:
          api-key: ${NEW_RELIC_API_KEY}

    processors:
      batch:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/datadog, otlphttp/newrelic]
