apiVersion: v1
kind: Service
metadata:
  name: nginxservice
  labels:
    app: {{ include "frontend.name" . }}
spec:
  selector:
    app: {{ include "frontend.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}       # External port
      targetPort: 80                         # Container port
  type: {{ .Values.service.type }}           # ClusterIP
