name: Deploy App on EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Add SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > terraform-key.pem
          chmod 600 terraform-key.pem

      - name: Install Python Dependencies
        run: pip install paramiko

      - name: Run EC2 Setup Script
        run: python scripts/setup_ec2.py
