name: "Terraform Deploy - Dev"

on:
  workflow_dispatch:    # manual trigger

jobs:
  terraform:
    name: Terraform Apply (Dev)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # specify your required version

      - name: Terraform Init
        working-directory: terraform/envs/dev
        run: terraform init

      - name: Terraform Format Check
        working-directory: terraform/envs/dev
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: terraform/envs/dev
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform/envs/dev
        run: terraform plan

      - name: Terraform Plan
        working-directory: terraform/envs/dev
        run: terraform apply -auto-approve
     

      
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION}}  # change this as needed
