name: Deploy via Ansible Order-service application

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    - name: Add SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Create dynamic inventory
      run: |
        echo "[ec2]" > ansible/hosts
        echo "${{ secrets.EC2_HOST }} ansible_user=${{ secrets.EC2_USER }} ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> ansible/hosts

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i ansible/hosts ansible/playbook.yml
